-- liquibase formatted sql

-- changeset Jaroslav:1
INSERT INTO Pharmacy (Name, Phone_Number, Address, Director_FullName)
VALUES ('Vita', '89264532020', 'Lukashenko 25', 'Vasiliy Vasilievich')
INSERT INTO Pharmacy (Pharmacy_Number, Name, Phone_Number, Address, Director_FullName)
VALUES ('Delta', '89274532020', 'Samarskaya 24', 'Ivan Ivanov')
INSERT INTO Pharmacy (Pharmacy_Number, Name, Phone_Number, Address, Director_FullName)
VALUES ('Life', '89284532020', 'Moskovskaya 23', 'Daniil Daniilovich')

INSERT INTO Goods (Name)
VALUES ('Парацатамол')
INSERT INTO Goods (Name)
VALUES ('Визим')
INSERT INTO Goods (Name)
VALUES ('Смекта')
INSERT INTO Goods (Name)
VALUES ('Назал')

INSERT INTO Characteristics (Name)
VALUES ('Спрей')
INSERT INTO Characteristics (Name)
VALUES ('От насморка')
INSERT INTO Characteristics (Name)
VALUES ('Для живота')
INSERT INTO Characteristics (Name)
VALUES ('Обезболивающее')
INSERT INTO Characteristics (Name)
VALUES ('Сильнодействующее')
INSERT INTO Characteristics (Name)
VALUES ('Слабодействующее')

INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (1, 4, 'Слабодействующее обезболивающее')
INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (1, 7, 'Слабодействующее обезболивающее')
INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (2, 4, 'Сильнодействующее обезболивающее')
INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (2, 6, 'Сильнодействующее обезболивающее')
INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (3, 3, 'Лекарство для живота')
INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (4, 2, 'Лекарство от насморка')
INSERT INTO GoodsCharacteristics (CharId, GoodsId, Description)
VALUES (4, 1, 'Лекарство от насморка')

INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (1, 1, 444, 20)
INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (1, 2, 234, 15)
INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (1, 3, 545, 23)
INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (2, 4, 234, 345)
INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (2, 2, 600, 435)
INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (3, 1, 444, 453)
INSERT INTO AvailableGoods (PharmacyId, GoodsId, Price, Amount)
VALUES (3, 3, 700, 700)
